language: ruby

before_script:
  - mysql -u root -e 'create database ar_inception; grant all privileges on ar_inception.* to "gemtests"@localhost identified by "rsanders";'
  - bundle exec rake appraisal:install
  - echo "Ran before_scripts"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 1.8.7
  - jruby


notifications:
  email:
    - robert@zeevex.com

script: bundle exec rake appraisal spec
