language: ruby

before_script:
  - mysql -u root -e 'create database ar_inception; grant all privileges on ar_inception.* to "rsanders"@localhost identified by "rsanders";'
  - echo "Ran before_scripts"

rvm:
  - 1.8.7

notifications:
  email:
    - robert@zeevex.com

script: bundle exec rake spec