services:
	- mysql
	
before_script:
  - mysql -e 'create database ar_inception; grant all privileges on ar_inception.* to "rsanders"@localhost identified by "rsanders";'

rvm:
  - 1.8.7
  - 1.9.3
  - jruby

script: "bundle exec rake rspec"
