
mysql:
  adapter: mysql
  hostname: localhost
  username: gemtests
  password: rsanders
  database: ar_inception
  pool: 30

jdbcmysql:
  adapter: jdbcmysql
  hostname: localhost
  username: gemtests
  password: rsanders
  database: ar_inception
  pool: 30

postgresql:
  adapter: postgresql
  hostname: localhost
  username: gemtests
  password: rsanders
  database: ar_inception
  pool: 30
